DSRbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Effort Controllers ---------------------------------------
  vertical_pos_controller:
    type: effort_controllers/JointPositionController
    joint: soporte1_joint
    pid: {p: 100.0, i: 100.0, d: 100.0}
  horizontal_pos_controller:
    type: effort_controllers/JointPositionController
    joint: carrier_joint
    pid: {p: 4.0, i: 0.1, d: 1.5}
